import assert from 'node:assert/strict';
const base=process.env.API_TEST_URL || 'http://127.0.0.1:3000';
if (!['127.0.0.1','localhost'].includes(new URL(base).hostname)) throw new Error('Smoke tests create fixture records: use a local test database.');
let checks=0;
async function req(path,token,method='GET',body,expected=200){const r=await fetch(base+path,{method,headers:{...(token?{Authorization:`Bearer ${token}`} :{}),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const j=await r.json();assert.equal(r.status,expected,`${method} ${path}: ${j.error || 'Unexpected response'}`);checks++;return j;}
const a=(await req('/api/auth/demo-session',null,'POST',{account:'ORGANISER_B'})).token;
const b=(await req('/api/auth/demo-session',null,'POST',{account:'PARTICIPANT_A'})).token;
await req('/api/me',null,'GET',null,401);await req('/api/me','invalid','GET',null,401);
await req('/api/events',a,'POST',{},400);
const event=(await req('/api/events',a,'POST',{title:'BANANA FESTIVAL',eventType:'Festival',description:'A celebration of bananas and the people who grow them.',startDate:'2026-12-20',endDate:'2026-12-21',timezone:'Asia/Kolkata',location:'Community gardens'},201)).event;
const id=event.id;
let c=await req(`/api/events/${id}/context`,a);assert.equal(c.venues.length,0);assert.equal(c.floors.length,0);assert.equal(c.sessions.length,0);assert.deepEqual(c.event.categories,[]);checks+=4;
await req(`/api/organiser/events/${id}/dashboard`,b,'GET',null,403);
const app=(await req(`/api/events/${id}/apply`,b,'POST',{applicantName:'Local Test Participant',institution:'Community collective',category:'Participant',statement:'I would like to attend this community celebration.'},201)).application;
const review=await req(`/api/organiser/applications/${app.id}/status`,a,'PATCH',{status:'ACCEPTED'});console.log('Review persisted:',Object.keys(review));
c=await req(`/api/events/${id}/context`,b);assert.equal(c.myApplication.status,'ACCEPTED');assert.ok(c.myCredential.verificationToken);checks+=2;
const verification=await req(`/api/verify/${c.myCredential.verificationToken}`);assert.equal(verification.valid,true);assert.equal('email' in verification,false);checks+=2;
await req(`/api/organiser/events/${id}/floors`,b,'POST',{name:'Garden',levelOrder:0},403);
const floor=(await req(`/api/organiser/events/${id}/floors`,a,'POST',{name:'Garden',levelOrder:0},201)).floor;
const venue=(await req(`/api/organiser/events/${id}/venues`,a,'POST',{floorId:floor.id,name:'Welcome desk',shortDescription:'Start your festival visit here',floor:'Garden',zone:'Entrance',poiType:'REGISTRATION',poiCategory:'EVENT',mapX:20,mapY:40},201)).venue;
await req(`/api/organiser/events/${id}/announcements`,a,'POST',{title:'Welcome to the festival',body:'Please arrive at the welcome desk.',audience:'ACCEPTED_ONLY',priority:'IMPORTANT'},201);
c=await req(`/api/events/${id}/context`,b);assert.ok(c.venues.some(v=>v.id===venue.id));assert.ok(c.floors.some(f=>f.id===floor.id));assert.ok(c.announcements.some(v=>v.title==='Welcome to the festival'));checks+=3;
const destination=(await req(`/api/organiser/events/${id}/venues`,a,'POST',{floorId:floor.id,name:'Fruit stand',shortDescription:'Fresh fruit for everyone',floor:'Garden',zone:'East',poiType:'FOOD',poiCategory:'AMENITY',mapX:75,mapY:50},201)).venue;
let route=await req(`/api/events/${id}/route?fromVenueId=${venue.id}&toVenueId=${destination.id}`,b);assert.equal(route.reachable,false);checks++;
await req(`/api/organiser/events/${id}/edges`,a,'POST',{fromVenueId:venue.id,toVenueId:destination.id,distanceMeters:12,accessible:true},201);
route=await req(`/api/events/${id}/route?fromVenueId=${venue.id}&toVenueId=${destination.id}&accessibleOnly=true`,b);assert.equal(route.reachable,true);assert.equal(route.totalDistanceMeters,12);checks+=2;
const sessionData={title:'Community welcome',description:'Meet the people who grow our food.',startTime:'10:00',endTime:'11:00',dayLabel:'Day 1',track:'General',venueId:null,status:'UP_NEXT'};
const session=(await req(`/api/organiser/events/${id}/sessions`,a,'POST',sessionData,201)).session;
await req(`/api/organiser/events/${id}/sessions/${session.id}`,a,'PUT',{...sessionData,venueId:destination.id});
c=await req(`/api/events/${id}/context`,b);assert.equal(c.sessions.find(s=>s.id===session.id).venueId,destination.id);checks++;
const food=await req('/api/ai/ask',b,'POST',{eventId:id,question:'Where is food?'});assert.match(food.answer,/Fruit stand/);assert.equal(food.provider,'event-state');checks+=2;
await req(`/api/organiser/events/${id}/config`,a,'PATCH',{visibility:'PRIVATE'});
const publicList=await req('/api/events');assert.equal(publicList.events.some(e=>e.id===id),false);checks++;
await req(`/api/events/${id}/context`,null,'GET',null,404);
const ownJourneys=await req('/api/me/journeys',a);assert.ok(ownJourneys.organising.some(j=>j.id===id));checks++;
const memberContext=await req(`/api/events/${id}/context`,b);assert.equal(memberContext.event.id,id);checks++;
const direct=await req('/api/ai/ask',b,'POST',{eventId:id,question:"What's next?"});assert.equal(direct.provider,'event-state');checks++;
await req('/api/ai/ask',null,'POST',{eventId:id,question:"What's next?"},404);
console.log(`${checks} integration assertions passed; event ${id}`);
